plugins {
    id 'com.android.application'
}

android {
    namespace 'com.reasonix.recipebook'
    compileSdk 34

    defaultConfig {
        applicationId "com.reasonix.recipebook"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
